name = "kungfu-ai"
main = "src/worker.ts"
account_id = "049ff5e84ecf636b53b162cbb580aae6"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "DOJO_KV"
id = "dc05fcbbc5d74d0c8d0cde0d8449ad80"
